### ISSUE TITLE
Document how to tune storage specs 

### ISSUE THREAD

**Issue by arajkumar** [timescale/promscale-benchmark#27]
Currently there is no preferred approach to tune storage configuration for benchmark environment. Documenting the same would help the user to play with difference storage types(gp2, gp3, io,.. etc), IOPS and throughput.

**Comment by arajkumar** [comment]
1. Create a new storage class with relevant parameters(type, iops, throughput),
```
cat << EOF | kubectl apply -f -
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: 16000
  throughput: 1000
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
EOF
```
2. Add `storageClass: gp3` property in [timescale-db values.yaml ](https://github.com/timescale/promscale-benchmark/blob/main/stack/values.yaml#L6-L10)
